//
// This code was generated by Visual ReCode 1.0.0.0
//

using System;
using System.Collections.Generic;

namespace HotelCore.Client
{
    public partial class Room
    {
        public int Number { get; set; }
        public int Floor { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
    }
}

