//
// This code was generated by Visual ReCode 1.0.0.0
//

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelCore.WcfProxy
{
    [System.ServiceModel.ServiceContract]
    public interface IHotelService
    {
        [System.ServiceModel.OperationContract]
        Task<IList<Room>> GetAvailableRooms(DateTimeOffset checkInDate, DateTimeOffset checkOutDate);

        [System.ServiceModel.OperationContract]
        Task<Room> GetRoom(int number);

        [System.ServiceModel.OperationContract]
        Task<Room[]> GetRooms(int[] numbers);

        [System.ServiceModel.OperationContract]
        IEnumerable<Room> AllRooms();

    }
}

